### ISSUE TITLE
It seems MarkdownHere renders latex formula by google web api, which is inavaliable here in mainland China. Is there any other alternative options?

### ISSUE THREAD

**Issue by luohc2004** [fei0810/markdownhere4zotero#2]
Since the option menu is not working under Zotero userinterface, if there exists one, how can I change that? may be by a config file?

**Comment by wtianyi** [comment]
You are welcome to try [my adaptation of markdown-here](https://github.com/wtianyi/markdown-here) that uses KaTeX for  HTML-only math equation rendering.

Please read the `README.md` and, especially, search for Zotero relate info there.

**Comment by luohc2004** [comment]
> 
> 
> You are welcome to try [my adaptation of markdown-here](https://github.com/wtianyi/markdown-here) that uses KaTeX for HTML-only math equation rendering.
> 
> Please read the `README.md` and, especially, search for Zotero relate info there.

Definiately I will try. That's great. I think maybe you can pull request to the main repo of Markdown-here~

**Comment by luohc2004** [comment]
> 
> 
> You are welcome to try [my adaptation of markdown-here](https://github.com/wtianyi/markdown-here) that uses KaTeX for HTML-only math equation rendering.
> 
> Please read the `README.md` and, especially, search for Zotero relate info there.

I referer to README.md and found that to user KaTeX for local equation rendering, I have to modify zotero's TinyMCE a little bit?  Would it be a problem when zotero update itself ?

**Comment by wtianyi** [comment]
Great! Let me know if you have trouble using it.

I thought about making a pull-request, but it seems that Markdown Here guys have thought through the possible options for changing the (obviously out-dated) math-rendering mechanism but decided CodeCogs is the way to go (see https://github.com/adam-p/markdown-here/issues/144#issuecomment-64654115). The reason is that KaTeX relies on special fonts to properly render, which is not generally feasible in rich-text editing scenarios (e.g. embedded equations in emails). Therefore, my adaptation deviates from the goal of Markdown Here and I think I might just leave the original repo as it is.

For the same reason, to make the KaTeX equations work properly in Zotero, one needs to hack the settings and resource files of the embedded TinyMCE editor in Zotero. You are right that this hack will not able to survive an update of Zotero...

On the other hand, I've tried to modify the Google charts API to CodeCogs. That modification would be as easy as a one-line change of the default math-rendering API in `'math-value'`. See

https://github.com/wtianyi/markdown-here/blob/f105982e8522eb27ab2fb03efc8b25de9d671e7d/src/common/options-store.js#L21-L22

**Note**: You'll need to make this change on the original Markdown Here repo, because I updated the `marked.js` library in my repo, and the math-rendering handling modifications in `marked.js` are lost, therefore my repo wouldn't work with the URL-API based math-rendering.

**Comment by luohc2004** [comment]
> 
> 
> Great! Let me know if you have trouble using it.
> 
> I thought about making a pull-request, but it seems that Markdown Here guys have thought through the possible options for changing the (obviously out-dated) math-rendering mechanism but decided CodeCogs is the way to go (see [adam-p/markdown-here#144 (comment)](https://github.com/adam-p/markdown-here/issues/144#issuecomment-64654115)). The reason is that KaTeX relies on special fonts to properly render, which is not generally feasible in rich-text editing scenarios (e.g. embedded equations in emails). Therefore, my adaptation deviates from the goal of Markdown Here and I think I might just leave the original repo as it is.
> 
> For the same reason, to make the KaTeX equations work properly in Zotero, one needs to hack the settings and resource files of the embedded TinyMCE editor in Zotero. You are right that this hack will not be able to survive an update of Zotero... Without the special fonts, the rendered formulas are still readable, just not so pretty...
> 
> On the other hand, I've tried to modify the Google charts API to CodeCogs. That modification would be as easy as a simple change of the default math-rendering API in `'math-value'`. See
> 
> https://github.com/wtianyi/markdown-here/blob/f105982e8522eb27ab2fb03efc8b25de9d671e7d/src/common/options-store.js#L21-L22
> 
> and see https://github.com/wtianyi/markdown-here/blob/f105982e8522eb27ab2fb03efc8b25de9d671e7d/src/common/default.css#L204-L207 for a sample of accompanying CSS-style to make the rendered equations as high as a line and vertically better-positioned.
> 
> **Note**: You'll need to make this change based on the original Markdown Here repo, because I updated the `marked.js` library in my repo, and the math-rendering handling modifications in `marked.js` are lost, therefore my repo wouldn't work with the URL-API-based math-rendering.

Thank you for your advice. I changed the value in options-store.js myself and learn a lot from you. Thanks a lot~
